#!/usr/bin/env bash
set -euo pipefail
IMAGE="${PRITHVI_CONTAINER_IMAGE:?Set an installed vendor runtime image identity}";ROOT="${PRITHVI_SYSTEM_ROOT:?Set the prepared system workspace}";OUT="${ROOT}/09_cold_start";TOOLS="${PRITHVI_REPO:?Set the repository root}/src/system";INPUT="${ROOT}/02_input/configuration_validation_input_00.npy";KMOD_NOOP="${PRITHVI_SHIM:?Set the compiled compatibility shim}"
test ! -e "${OUT}";mkdir -p "${OUT}";printf 'measuring\n'>"${OUT}/RUN_STATUS"
stable_idle(){ local n=0;while ((n<5));do if test -z "$(docker ps -q)"&&test -z "$(ls -A /sys/class/kfd/kfd/proc 2>/dev/null||true)";then n=$((n+1));else n=0;fi;sleep 1;done;}
run_one(){ local trial="$1" label="$2" token="$3" config="$4";local dir="${OUT}/${token}/trial_$(printf '%02d' "$trial")" cname="flood-cold-${token}-${trial}-$$" cid rc stop;stable_idle;mkdir -p "${dir}";stop="${dir}/sampler.stop";python3 "${TOOLS}/telemetry.py" --stop "$stop" --output "${dir}/telemetry.csv" --interval .2 & sampler=$!;sleep 1;printf '%s\n' "$(date +%s%N)">"${dir}/container_launch_unix_ns.txt";cid=$(docker run --network none --hostname "$(hostname)" --entrypoint python3 --pids-limit 1024 --device=/dev/kfd --device=/dev/dri --group-add video --ipc=host --shm-size=8g -v /opt/hyhal:/opt/hyhal:ro -v "${PRITHVI_WORKSPACE:?Set a common ancestor of code, assets and outputs}:${PRITHVI_WORKSPACE}:rw" -e PRITHVI_HWMON -e PRITHVI_DEVICE_SYSFS -v "${KMOD_NOOP}:/bin/kmod:ro" -v "${KMOD_NOOP}:/usr/sbin/lsmod:ro" -e MIGRAPHX_GPU_COMPILE_PARALLEL=1 -e ORT_MIGRAPHX_EXHAUSTIVE_TUNE=0 -e OMP_NUM_THREADS=1 -e OPENBLAS_NUM_THREADS=1 -e MKL_NUM_THREADS=1 -e NUMEXPR_NUM_THREADS=1 -e MALLOC_ARENA_MAX=2 --name "$cname" -d "$IMAGE" "$TOOLS/flood_cold.py" --label "$label" --config "$config" --input "$INPUT" --output-dir "${dir}/run");printf '%s\n' "$cid">"${dir}/container_id.txt";set +e;rc=$(docker wait "$cid");set -e;printf '%s\n' "$(date +%s%N)">"${dir}/container_exit_unix_ns.txt";docker logs "$cid">"${dir}/container.log" 2>&1||true;docker rm "$cid">/dev/null;sleep 1;touch "$stop";wait "$sampler";test "$rc" = 0;test -s "${dir}/run/result.json";echo "$(date --iso-8601=seconds) trial=$trial variant=$label cold_passed"|tee -a "${OUT}/progress.log";}
FP32="$ROOT/00_configs/Mono_FP32.json";FP16="$ROOT/00_configs/Mono_FP16_Opt.json";MP="$ROOT/00_configs/MP_RCS_Opt.json"
for t in $(seq 1 10);do case $((t%3)) in 1) run_one "$t" Mono-FP32 Mono_FP32 "$FP32";run_one "$t" Mono-FP16-Opt Mono_FP16_Opt "$FP16";run_one "$t" MP-RCS-Opt MP_RCS_Opt "$MP";;2) run_one "$t" Mono-FP16-Opt Mono_FP16_Opt "$FP16";run_one "$t" MP-RCS-Opt MP_RCS_Opt "$MP";run_one "$t" Mono-FP32 Mono_FP32 "$FP32";;0) run_one "$t" MP-RCS-Opt MP_RCS_Opt "$MP";run_one "$t" Mono-FP32 Mono_FP32 "$FP32";run_one "$t" Mono-FP16-Opt Mono_FP16_Opt "$FP16";;esac;done
stable_idle;find "$OUT" -type f ! -name SHA256SUMS.txt ! -name RUN_STATUS -print0|sort -z|xargs -0 sha256sum>"$OUT/SHA256SUMS.txt";printf 'PASSED\n'>"$OUT/RUN_STATUS"
